---

- hosts: localhost
  connection: local

  pre_tasks:
    - name: pre | pre_tasks
      become: true
      block:
        - name: pre | update apt
          apt:
            update_cache: true
          changed_when: False
      rescue:
        - set_fact: task_failed=true
      tags: always

    - name: pre | store architecture in fact
      block:
        - name: pre | dpkg architecture
          shell: dpkg --print-architecture
          register: architecture_command_output

        - name: pre | display architecture
          debug:
            var: architecture_command_output.stdout

        - name: "pre | set_fact custom_architecture dpkg --print-architecture"
          set_fact:
            custom_architecture: "{{ architecture_command_output.stdout }}"
      rescue:
        - set_fact: task_failed=true

- hosts: localhost
  become: true
  roles:
    - base