---

- name: LOCAL SETUP
  hosts: localhost
  connection: local

  pre_tasks:
    - name: update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core

  tasks:
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/git-setup.yml
    - include: tasks/aws-setup.yml
    - include: tasks/aws-vault-setup.yml