---
- name: git config email
  git_config:
    name: user.email
    scope: global
    value: "tobias.foerg@sunny-systems.com"
- name: git config name
  git_config:
    name: user.name
    scope: global
    value: "Tobias Förg"